### ISSUE TITLE
Colors do not offer a lightness variation

### ISSUE THREAD

**Issue by beefchimi** [dfmcphee/threads-foundation#1]
Curious why you chose to omit the option for color `value` in the map / function. You do retain the comment for it.

<details>
<summary>

<strong>Full blown colour</strong></summary>

``` scss
// ==|== colors ================================================================
// =============================================================================

// Maps
// -----------------------------------------------------------------------------
$default-color-palette-data: (
  white: (
    base: #fff,
  ),
  black: (
    base: #000,
  ),
  ash: (
    lightest: #fcfcfc,
    lighter: #fafbfc,
    light: #f5f6f7,
    base: #ebeef0,
    dark: #d3dbe2,
    darker: #c3cfd8,
    darkest: #a9b8c4,
  ),
  coal: (
    lightest: #95a7b7,
    lighter: #798c9c,
    light: #454e57,
    base: #31373d,
    dark: #272c30,
    darker: #212529,
    darkest: #0e0d0e,
  ),
  ink: (
    lightest: hsla(0, 0%, 0%, 0.58),
    lighter: hsla(0, 0%, 0%, 0.64),
    light: hsla(0, 0%, 0%, 0.7),
    base: hsla(0, 0%, 0%, 0.76),
    dark: hsla(0, 0%, 0%, 0.82),
    darker: hsla(0, 0%, 0%, 0.88),
    darkest: hsla(0, 0%, 0%, 0.94),
  ),
  green: (
    lightest: #eafdf7,
    lighter: #c3f9e4,
    light: #78ecbc,
    base: #29bc94,
    dark: #15966d,
    darker: #186148,
    darkest: #134230,
  ),
  blue: (
    lightest: #eff9fd,
    lighter: #c0effb,
    light: #57b8ff,
    base: #0042ff,
    dark: #0341dd,
    darker: #0439bc,
    darkest: #073199,
  ),
  purple: (
    lightest: #faf1fe,
    lighter: #eccdff,
    light: #d098ff,
    base: #b762ff,
    dark: #763eaf,
    darker: #4a1f72,
    darkest: #341851,
  ),
  red: (
    lightest: #fef6f5,
    lighter: #ffd9d6,
    light: #ff9797,
    base: #ff5d5d,
    dark: #d83e3e,
    darker: #852929,
    darkest: #662121,
  ),
  orange: (
    lightest: #fff9ec,
    lighter: #ffebcc,
    light: #fec97d,
    base: #ff9517,
    dark: #e06b0c,
    darker: #7f3a07,
    darkest: #5e2b08,
  ),
  yellow: (
    lightest: #fffbe9,
    lighter: #fff7b2,
    light: #ffe477,
    base: #f9e717,
    dark: #ffd117,
    darker: #d4a002,
    darkest: #6f4f0c,
  ),
);

$custom-color-palette-data: () !default;

// Functions
// -----------------------------------------------------------------------------
// Returns the color value for a given color name and group.
// @param {String} $hue - The color's hue.
// @param {String} $value - The darkness/lightness of the color. Defaults to base.
// @param {Color} $for-background - The background color on which this color will
// appear. Applies a multiply filter to ensure appropriate contrast.
// @return {Color} The color value.
@function color($hue, $value: base, $for-background: null) {
  // merge custom color palette
  $color-palette-data: map-merge($default-color-palette-data, $custom-color-palette-data);

  // fetch color from map
  $fetched-color: map-get(map-get($color-palette-data, $hue), $value);

  // if fetched value matches another key
  @if map-has-key($color-palette-data, $fetched-color) {
    // get color with fetched key
    $fetched-color: map-get(map-get($color-palette-data, $fetched-color), $value);
  }

  @if $for-background != null {
    $fetched-color: color-multiply($fetched-color, $for-background);
  }

  @if type-of($fetched-color) == color {
    @return $fetched-color;
  } @else {
    @error "Color `#{$hue} - #{$value}` not found. Available colors: #{available-names($color-palette-data)}";
  }
}

// Darkens the foreground color by the background color.
// This is the same as the “multiply” filter in graphics apps.
// @param {Color} $foreground - The color to darken.
// @param {Color} $background - The background to base darkening on.
// @return {Color} The modified color.
@function color-multiply($foreground, $background: null) {
  @if $background == null {
    $background: #fff;
  }

  @return $foreground * $background / 255;
}

// Determine strength of inset shadow based on background color
// @param {Color} $color - The color to match shadow opacity against
// @return {Number} The decimal value of opacity
@function inset-shadow($color) {
  @if (lightness($color) > 80 or opacity($color) < 0.5) {
    @return 0.1;
  } @else {
    @return 0.2;
  }
}
```

</details>
