### ISSUE TITLE
Consider a z-index map + function?

### ISSUE THREAD

**Issue by beefchimi** [dfmcphee/threads-foundation#2]
Similar to everything else, perhaps worth including a `zindex.scss` with standard defaults like `nav`, `header`, `footer`, etc?

<details>
<summary>

<strong>le exampé</strong></summary>

``` scss
// ==|== z-index ===============================================================
// =============================================================================

// Maps
// -----------------------------------------------------------------------------
$default-z-index-data: (
  main: 1,
  header: 2,
  footer: 3,
  nav: 4,
);

$custom-z-index-data: () !default;

// Functions
// -----------------------------------------------------------------------------
// Returns the z-index value for a given variant.
// @param {String} $variant - The key for the given variant.
// @return {Number} The z-index value for the variant.
@function z-index($variant: base) {
  // merge custom color palette
  $z-index-data: map-merge($default-z-index-data, $custom-z-index-data);

  $fetched-value: map-get($z-index-data, $variant);

  @if $fetched-value != null {
    @return $fetched-value;
  } @else {
    @error "z-index variant `#{$variant}` not found. Available variants: #{available-names($z-index-data)}";
  }
}
```

</details>
